import image1 from './images/food-img1.jpg';
import image2 from './images/food-img2.jpg';
import image3 from './images/food-img3.jpg';
import image4 from './images/food-img4.jpg';
import image5 from './images/food-img5.jpg';
import image6 from './images/food-img6.jpg';
import image7 from './images/food-img7.jpg';
import image8 from './images/food-img8.jpeg';
import image9 from './images/food-img9.jpg';
import image10 from './images/food-img10.jpeg';
import image11 from './images/food-img11.jpeg';
import image12 from './images/food-img12.jpg';

export const img1 = image1;
export const img2 = image2;
export const img3 = image3;
export const img4 = image4;
export const img5 = image5;
export const img6 = image6;
export const img7 = image7;
export const img8 = image8;
export const img9 = image9;
export const img10 = image10;
export const img11 = image11;
export const img12 = image12;
